# Generated by Django 3.0.8 on 2020-07-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataURL',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('data_hash', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
